apiVersion: v1
kind: Namespace
metadata:
  name: website-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: website-system
  labels:
    type: backend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: pear1798/backend:stableCpuV2
        ports:
        - containerPort: 5000
        command: ["python3"]
        args: ["backend.py"]
        

---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: website-system
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backend-role
rules:
- apiGroups: [""] 
  resources: ["namespaces"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: ["apps"] 
  resources: ["deployments"]
  verbs: ["get", "watch", "list", "create", "update", "delete"]
- apiGroups: [""] 
  resources: ["pods"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: [""] 
  resources: ["services"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["create"]

  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backend-rolebinding
subjects:
- kind: ServiceAccount
  name: default
  namespace: website-system
  
roleRef:
  kind: ClusterRole        
  name: backend-role 
  apiGroup: rbac.authorization.k8s.io
